apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  namespace: 2048-app

spec:
  replicas: 2  
  selector:
    matchLabels:
      app: 2048-ws
  template:
    metadata:
      labels:
        app: 2048-ws
    spec:
      containers:
      - name: 2048-container
        image: blackicebird/2048  
        ports:
        - containerPort: 80
