apiVersion: v1
kind: Service
metadata:
  name: coin-change-calc-service  
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify NLB
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-02b03655a76056bcd"
    
spec:
  selector:
    app: coin-change-calc
  ports:

    - protocol: TCP
      port: 80  
      targetPort: 3000
  type: LoadBalancer